version: '3.8'
services:
  auth:
    build:
      args:
        GO_PUZZLE_SERVICE: billiard:v1.0.0 
    image: billiard-server:latest
    restart: always
    container_name: billiard-server 
    network_mode: host
    command:
      - ./server
      - --useRemoteConfig
    logging:
      options:
        max-size: 100m
