version: '3.8'
services:
  auth:
    build:
      args:
        GO_PUZZLE_SERVICE: billiard:v1.0.0 
    image: billiard-server:latest
    restart: always
    container_name: billiard-server 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 29920:29920
    networks:
      - yong-network
    command:
      - ./server
      - --useRemoteConfig
    logging:
      options:
        max-size: 100m

networks:
  yong-network:
    external: true
    name: yong-network
