conf:
  avatarDir: "avatar"
  userApi: "https://billiard.superwhys.top/api/v1/user"
  # 30d
  tokenTtl: 816h 
redisAuth:
  server: localhost:6379
  db: 10
mysqlAuth:
  instance: localhost:3306
  database: snooker
  username: root
  password: yang4869
minioAuth:
  # endpoint: minio-api 
  # accessKey: YbZOX5qJ15ZQaKUsLLpe 
  # secretKey: lBit97vxQMbye2Cf3pDcb2EFNqQeH1iNJm1DqTZH
  # bucket: snooker-assistant
  endpoint: 10.11.43.115:9000 
  accessKey: jRdUastUrl69Nn1Zv6CZ 
  secretKey: EooHGXHOp8CFDZlKoczzKtJ3WO8pNv9167PDuwx5
  bucket: snooker-assistant
wxAppId: wx7920f25bceaf0457
wxAppSecret: 30c97c35830bad2bb74f265f1ed83900
